apiVersion: v2
name: garage
description: S3-compatible object store for small self-hosted geo-distributed deployments.
type: application
version: 0.1.0
appVersion: "v2.1.0"
dependencies:
  - name: common
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: JTreske
