apiVersion: v2
name: docmost
description: Docmost is an open-source collaborative wiki and documentation software.
type: application
version: 0.1.3
appVersion: "0.23.2"
dependencies:
  - name: common
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: JTreske
