apiVersion: v2
name: tandoor
description: The recipe manager that allows you to manage your ever growing collection of digital recipes.
type: application
version: 0.2.0
appVersion: "2.3.5"
dependencies:
  - name: common
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: JTreske
